version: '3.8'

services:

  db:
    container_name: postgres_ariys
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ariys
      POSTGRES_USER: ariys
      POSTGRES_DB: ariys
      PGDATA: /home/postgres/pgdata/data
    volumes:
      - ~/.murine/ariys/postgres-data:/home/postgres/pgdata/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ariys" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ariys:
    container_name: ariys_be
    build:
      context: .
      dockerfile: be.Dockerfile
    env_file:
      - .local.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=ariys
      - DATABASE_USER=ariys
      - DATABASE_PASSWORD=ariys
      - ALLOWED_HOSTS=127.0.0.1,localhost,*
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1,http://*
      - CORS_ALLOWED_ORIGINS=*
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    links:
      - db
    command: sh -c "scripts/run_service.sh"
#    command: tail -f /dev/null
