[tool.black]
line-length = 100
exclude = '''
/(
  | migrations
  | \.git
  | \.github
  | node_modules
  | mypy_cache
  | .venv
)/

'''


[tool.isort]
profile = "black"
multi_line_output = 3
skip = [".gitignore", ".dockerignore", "lambda_handler.py"]
extend_skip = ["migrations"]
known_third_party = ["redis"]
